
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor Jafet Cruz
 */
public class Menu_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Menu Administrador
     */
    public Menu_Administrador() {
        initComponents();
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) CB_GenerosLibro.getModel();
        modelo.addElement("Default");
        modelo.addElement("Fantasia");
        modelo.addElement("Romance");
        modelo.addElement("Acción");
        modelo.addElement("Historia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTF_Titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTF_Autor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTf_CopiasDisp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTF_Descripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTF_Valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTF_Puntaje = new javax.swing.JTextField();
        Edicion = new javax.swing.JLabel();
        JTF_Edicion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTF_APublicacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CB_GenerosLibro = new javax.swing.JComboBox<>();
        JB_CrearLibro = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        CB_ModificarLibro = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        CB_ModificarUsuario = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        JB_EliminarListaLibro = new javax.swing.JButton();
        JB_LimpiarListaLibro = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        CB_ListarLibro = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_Libros = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        JB_EliminarListaUsuario = new javax.swing.JButton();
        JB_LimpiarListaUsuario = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        CB_ListarUsuario = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        JT_Usuario = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        CB_EliminarLibro = new javax.swing.JComboBox<>();
        JB_EliminarLibros = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        CB_EliminarUsuario = new javax.swing.JComboBox<>();
        JB_EliminarUsuario = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo");

        jLabel2.setText("Autor");

        jLabel3.setText("Copias Disponibles");

        JTf_CopiasDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTf_CopiasDispActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion");

        jLabel5.setText("Valor");

        jLabel6.setText("Puntaje");

        Edicion.setText("Edicion");

        jLabel7.setText("Año de Publicacion");

        jLabel8.setText("Generos");

        JB_CrearLibro.setText("Crear Libro");
        JB_CrearLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_CrearLibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(Edicion)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_Autor)
                    .addComponent(JTf_CopiasDisp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTF_Descripcion)
                    .addComponent(JTF_APublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(JTF_Edicion)
                    .addComponent(JTF_Puntaje)
                    .addComponent(JTF_Valor)
                    .addComponent(JTF_Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CB_GenerosLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_CrearLibro)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(238, 238, 238))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTF_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CB_GenerosLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTf_CopiasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTF_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTF_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTF_Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edicion)
                    .addComponent(JTF_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTF_APublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CrearLibro))
                .addGap(12, 12, 12))
        );

        jTabbedPane2.addTab("Crear Libro", jPanel1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", jPanel10);

        CB_ModificarLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(CB_ModificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CB_ModificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar Libro", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(CB_ModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CB_ModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar Usuario", jPanel3);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel14);

        JB_EliminarListaLibro.setText("Eliminar");
        JB_EliminarListaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarListaLibroMouseClicked(evt);
            }
        });

        JB_LimpiarListaLibro.setText("Limpiar");
        JB_LimpiarListaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_LimpiarListaLibroMouseClicked(evt);
            }
        });

        jLabel36.setText("Libro");

        CB_ListarLibro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_ListarLibroItemStateChanged(evt);
            }
        });

        JT_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Genero", "Puntaje", "Edicion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JT_Libros);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_ListarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 647, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JB_EliminarListaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(JB_LimpiarListaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_ListarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(JB_EliminarListaLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(JB_LimpiarListaLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Listar Libro", jPanel4);

        JB_EliminarListaUsuario.setText("Eliminar");
        JB_EliminarListaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarListaUsuarioMouseClicked(evt);
            }
        });

        JB_LimpiarListaUsuario.setText("Limpiar");
        JB_LimpiarListaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_LimpiarListaUsuarioMouseClicked(evt);
            }
        });

        jLabel35.setText("Usuario");

        CB_ListarUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_ListarUsuarioItemStateChanged(evt);
            }
        });

        JT_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha Nacimiento", "Numero Telefonico", "Correo", "Genero Favorito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JT_Usuario);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_ListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 647, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JB_EliminarListaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(JB_LimpiarListaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_ListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(JB_EliminarListaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(JB_LimpiarListaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Listar Usuario", jPanel5);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel17);

        JB_EliminarLibros.setText("ELIMINAR ELEMENTO SELECCIONADO");
        JB_EliminarLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarLibrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_EliminarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(CB_EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(JB_EliminarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("ELiminar Libro", jPanel6);

        JB_EliminarUsuario.setText("ELIMINAR ELEMENTO SELECCIONADO");
        JB_EliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(CB_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(JB_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Eliminar Usuario", jPanel7);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel13);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_EliminarListaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarListaUsuarioMouseClicked
        if (JT_Usuario.getSelectedRow() >= 0) {
            DefaultTableModel modelo
            = (DefaultTableModel) JT_Usuario.getModel();
            modelo.removeRow(JT_Usuario.getSelectedRow());
            JT_Usuario.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }

    }//GEN-LAST:event_JB_EliminarListaUsuarioMouseClicked

    private void JB_LimpiarListaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_LimpiarListaUsuarioMouseClicked
        JT_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Nombre", "Fecha Nacimiento", "Numero Telefonico", "Correo", "Genero Favorito"
            }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }//GEN-LAST:event_JB_LimpiarListaUsuarioMouseClicked

    private void CB_ListarUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_ListarUsuarioItemStateChanged
        if (evt.getStateChange() == 2) {
            Usuarios u = (Usuarios)
            CB_ListarUsuario.getSelectedItem();
            Object[] newrow = {
                u.getNombre_completo(),
                u.getFecha_n(),
                u.getNumero_tel(),
                u.getCorreo(),
                u.getGenero()

            };
            DefaultTableModel modelo
            = (DefaultTableModel) JT_Usuario.getModel();
            modelo.addRow(newrow);
            JT_Usuario.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }

    }//GEN-LAST:event_CB_ListarUsuarioItemStateChanged

    private void JB_EliminarListaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarListaLibroMouseClicked
       if (JT_Libros.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) JT_Libros.getModel();
            modelo.removeRow(JT_Libros.getSelectedRow());
            JT_Libros.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }
    }//GEN-LAST:event_JB_EliminarListaLibroMouseClicked

    private void JB_LimpiarListaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_LimpiarListaLibroMouseClicked
       JT_Libros.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Titulo", "Autor", "Genero", "Puntaje", "Edicion"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }//GEN-LAST:event_JB_LimpiarListaLibroMouseClicked

    private void CB_ListarLibroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_ListarLibroItemStateChanged
        if (evt.getStateChange() == 2) {
            Libros l = (Libros)
            CB_ListarLibro.getSelectedItem();
            Object[] newrow = {
                l.getTitulo(),
                l.getAutor(),
                l.getGenero(),
                l.getPuntaje(),
                l.getEdicion()

            };
            DefaultTableModel modelo
            = (DefaultTableModel) JT_Libros.getModel();
            modelo.addRow(newrow);
            JT_Libros.setModel(modelo);
            //tf_edad_maxima.setText(maxima_edad());
        }

    }//GEN-LAST:event_CB_ListarLibroItemStateChanged

    private void JB_EliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarUsuarioMouseClicked
        // TODO add your handling code here:
        int selecccionar1=JOptionPane.showConfirmDialog(this, "Desea Eliminar Este Usuario?");
        if(selecccionar1==0)
        {
            //Declarar los Modelos
            DefaultComboBoxModel cb_1 = (DefaultComboBoxModel)CB_EliminarUsuario.getModel();
            DefaultComboBoxModel cb_2 = (DefaultComboBoxModel)CB_ListarUsuario.getModel();
            DefaultComboBoxModel cb_3 = (DefaultComboBoxModel)CB_ModificarUsuario.getModel();
            
            //Eliminar elemento seleccionado del Combo Box            
            cb_1.removeElementAt(CB_EliminarUsuario.getSelectedIndex()+1);
            cb_2.removeElementAt(CB_ListarUsuario.getSelectedIndex()+1);
            cb_1.removeElementAt(CB_ModificarUsuario.getSelectedIndex()+1);
            
            //Volver a Setear el Modelo
            CB_EliminarUsuario.setModel(cb_1);
            CB_ListarUsuario.setModel(cb_2);
            CB_ModificarUsuario.setModel(cb_3);

        }//fin del if que valida el joption
        if (selecccionar1==1){
            JOptionPane.showMessageDialog(this, "Bueno, a la Proxima Decidase Antes!!!!");
        }
    }//GEN-LAST:event_JB_EliminarUsuarioMouseClicked

    private void JB_EliminarLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarLibrosMouseClicked
       int selecccionar=JOptionPane.showConfirmDialog(this, "Desea Eliminar Este Usuario?");
        if(selecccionar==0)
        {
            //Declarar los Modelos
            DefaultComboBoxModel cb_1 = (DefaultComboBoxModel)CB_EliminarLibro.getModel();
            DefaultComboBoxModel cb_2 = (DefaultComboBoxModel)CB_ListarLibro.getModel();
            DefaultComboBoxModel cb_3 = (DefaultComboBoxModel)CB_ModificarLibro.getModel();
            
            //Eliminar elemento seleccionado del Combo Box            
            cb_1.removeElementAt(CB_EliminarLibro.getSelectedIndex()+1);
            cb_2.removeElementAt(CB_ListarLibro.getSelectedIndex()+1);
            cb_1.removeElementAt(CB_ModificarLibro.getSelectedIndex()+1);
            
            //Volver a Setear el Modelo
            CB_EliminarLibro.setModel(cb_1);
            CB_ListarLibro.setModel(cb_2);
            CB_ModificarLibro.setModel(cb_3);

        }//fin del if que valida el joption
        if (selecccionar==1){
            JOptionPane.showMessageDialog(this, "Bueno, a la Proxima Decidase Antes!!!!");
        }
    }//GEN-LAST:event_JB_EliminarLibrosMouseClicked

    private void JTf_CopiasDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTf_CopiasDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTf_CopiasDispActionPerformed

    private void JB_CrearLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearLibroMouseClicked
         int puntaje, copia_d;
        double valor;
        String edicion, autor, genero, titulo, descripcion;
        int a_publicacion;
        titulo = JTF_Titulo.getText();
        descripcion = JTF_Descripcion.getText();
        autor = JTF_Autor.getText();
        edicion = JTF_Edicion.getText();
        puntaje = Integer.parseInt(JTF_Puntaje.getText());
        a_publicacion = Integer.parseInt(JTF_APublicacion.getText());
        copia_d = Integer.parseInt(JTf_CopiasDisp.getText());
        valor = Integer.parseInt(JTF_Valor.getText());
        Object obj = CB_GenerosLibro.getSelectedItem();
        genero = "";
        genero += obj;
        libro.add(new Libros(puntaje, copia_d, valor, edicion, autor, genero, titulo, descripcion, a_publicacion));
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) CB_ModificarLibro.getModel();
            modelo.addElement(new Libros(puntaje, copia_d, valor, edicion, autor, genero, titulo, descripcion, a_publicacion));
        CB_ModificarLibro.setModel(modelo);
        CB_EliminarLibro.setModel(modelo);
        CB_ListarLibro.setModel(modelo);
        JTF_APublicacion.setText("");
        JTF_Autor.setText("");
        JTF_Descripcion.setText("");
        JTF_Edicion.setText("");
        JTF_Puntaje.setText("");
        JTf_CopiasDisp.setText("");
        JTF_Valor.setText("");
        JTF_Titulo.setText("");
        
        JOptionPane.showMessageDialog(this, "Se ha Agregado Correctamente");
        
        
        
     
    }//GEN-LAST:event_JB_CrearLibroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_EliminarLibro;
    private javax.swing.JComboBox<String> CB_EliminarUsuario;
    private javax.swing.JComboBox<String> CB_GenerosLibro;
    private javax.swing.JComboBox CB_ListarLibro;
    private javax.swing.JComboBox CB_ListarUsuario;
    private javax.swing.JComboBox<String> CB_ModificarLibro;
    private javax.swing.JComboBox<String> CB_ModificarUsuario;
    private javax.swing.JLabel Edicion;
    private javax.swing.JButton JB_CrearLibro;
    private javax.swing.JButton JB_EliminarLibros;
    private javax.swing.JButton JB_EliminarListaLibro;
    private javax.swing.JButton JB_EliminarListaUsuario;
    private javax.swing.JButton JB_EliminarUsuario;
    private javax.swing.JButton JB_LimpiarListaLibro;
    private javax.swing.JButton JB_LimpiarListaUsuario;
    private javax.swing.JTextField JTF_APublicacion;
    private javax.swing.JTextField JTF_Autor;
    private javax.swing.JTextField JTF_Descripcion;
    private javax.swing.JTextField JTF_Edicion;
    private javax.swing.JTextField JTF_Puntaje;
    private javax.swing.JTextField JTF_Titulo;
    private javax.swing.JTextField JTF_Valor;
    private javax.swing.JTable JT_Libros;
    private javax.swing.JTable JT_Usuario;
    private javax.swing.JTextField JTf_CopiasDisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
String admin;
ArrayList<Libros> libro =new ArrayList();
public void admin(String admin){
    this.admin=admin;
}
ArrayList<Usuarios>usuar=new ArrayList();
Usuarios u= new Usuarios();
public void User (ArrayList<Usuarios>ut){
    this.usuar=ut;
}
public void us(Usuarios u){
    this.u=u;
}
}
